server:
    port: ${GENERAL_SERVICE_REGISTRY_SERVER_PORT}
spring:
    cloud:
        loadbalancer:
            enabled: true
    application:
        name: general-service-registry
eureka:
    instance:
        hostname: ${GENERAL_SERVICE_REGISTRY_SERVER_HOSTNAME}
    client:
        register-with-eureka: false
        fetch-registry: false
logging:
    level:
        com.netflix.eureka: OFF
        com.netflix.discovery: OFF